//
// Created by kindr on 2021/5/8.
//

#ifndef LEARNCUDA_MULTIKERNELCONCURRENT_CUH
#define LEARNCUDA_MULTIKERNELCONCURRENT_CUH

void multiKernelConcurrent();

#endif //LEARNCUDA_MULTIKERNELCONCURRENT_CUH
